/**
 * Rendering DA documents: the shape Document Authoring stores, produced from a fixture spec.
 *
 * The format was read off real documents rather than inferred (see .claude/qa/design-sources.md).
 * Everything in DA is one model:
 *
 *   <body><header></header>
 *     <main>
 *       <div>                          a section
 *         <div class="block variant">  a block; variants are extra class tokens
 *           <div><div>cell</div></div> rows, then cells
 *   <footer></footer></body>
 *
 * There are no tables. Page metadata is `div.metadata` and section metadata
 * `div.section-metadata`, both key/value rows — so metadata needs no special case.
 *
 * No I/O here: everything is a pure string transform, so the awkward part (the nav surgery) is
 * testable against a captured document instead of against a client's live content.
 */

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/* --------------------------------------------------------------- primitives */

/** Rows of [key, value] become a metadata-shaped block. */
export function metadataBlock(entries, className = 'metadata') {
  const rows = Object.entries(entries || {})
    .map(([k, v]) => `<div><div><p>${esc(k)}</p></div><div><p>${esc(v)}</p></div></div>`)
    .join('\n');
  return `<div class="${className}">\n${rows}\n</div>`;
}

/** A block: class tokens, then one div per row, one div per cell. */
export function block({ name, variants = [], rows = [] }) {
  const cls = [name, ...variants].filter(Boolean).join(' ');
  const body = rows
    .map((cells) => `<div>${cells.map((c) => `<div>${c}</div>`).join('')}</div>`)
    .join('\n');
  return `<div class="${cls}">\n${body}\n</div>`;
}

/** Wrap sections into the document DA expects. */
export function document_({ sections = [] }) {
  const main = sections.map((s) => `<div>\n${s}\n</div>`).join('\n');
  return `<body>\n<header></header>\n<main>\n${main}\n</main>\n<footer></footer>\n</body>`;
}

/**
 * A fixture page. It carries almost no content of its own — its job is to set metadata (the `nav`
 * override, the `Language` row that drives RTL) and to say what it is, so anyone who stumbles on
 * it in DA knows it is generated and where it came from.
 */
export function fixturePage(fixture, { source } = {}) {
  const heading = [
    `<h2>QA fixture — ${esc(fixture.id)}</h2>`,
    `<p>${esc(fixture.title)}${fixture.purpose ? ` — ${esc(fixture.purpose)}` : ''}</p>`,
    `<p><em>Generated by da-fixture.mjs${source ? ` from ${esc(source)}` : ''}. Do not edit by hand:`
      + ' edit the plan and re-run, or the next run will overwrite you.</em></p>',
  ].join('\n');

  const sections = [heading];
  if (fixture.metadata && Object.keys(fixture.metadata).length) sections.push(metadataBlock(fixture.metadata));
  for (const s of fixture.sections || []) {
    sections.push(block(s));
  }
  return document_({ sections });
}

/* ------------------------------------------------------------- nav surgery */

/**
 * Find the run of image-only links that the implementation classifies as the brand carousel.
 *
 * The strip is not a named block — AC-11 says "a strip of 2+ image-only links renders as the
 * brand carousel", so classification is by content shape at runtime. That means a fixture cannot
 * target it by class; it has to find the same thing the block's own code finds.
 *
 * @returns {{start:number, end:number, links:string[]}|null}
 */
export function findBrandStrip(html) {
  const LINK = /<a\b[^>]*>\s*<picture>[\s\S]*?<\/picture>\s*<\/a>/g;
  const hits = [];
  let m;
  while ((m = LINK.exec(html))) hits.push({ start: m.index, end: LINK.lastIndex, text: m[0] });
  if (hits.length < 2) return null;

  // Consecutive means "separated only by markup, not by other content" — the links sit in
  // sibling paragraphs, so only tags and whitespace may appear between them.
  let run = [hits[0]];
  let best = run;
  for (let i = 1; i < hits.length; i += 1) {
    const between = html.slice(hits[i - 1].end, hits[i].start);
    if (/^[\s]*(<\/?[a-z][^>]*>[\s]*)*$/i.test(between)) run.push(hits[i]);
    else run = [hits[i]];
    if (run.length > best.length) best = run;
  }
  if (best.length < 2) return null;
  return { start: best[0].start, end: best[best.length - 1].end, links: best.map((h) => h.text) };
}

/** Rewrite one link's alt text, and optionally its image source. */
export function editLink(link, { alt, src, caption } = {}) {
  let out = link;
  if (alt !== undefined) out = out.replace(/alt="[^"]*"/g, `alt="${esc(alt)}"`);
  if (src !== undefined) {
    out = out.replace(/src="[^"]*"/g, `src="${esc(src)}"`).replace(/srcset="[^"]*"/g, `srcset="${esc(src)}"`);
  }
  // A caption turns an image-only link into a captioned one, which the implementation must then
  // classify as featured products rather than as a brand carousel.
  if (caption) out = `${out}\n<p>${esc(caption)}</p>`;
  return out;
}

/**
 * Produce a nav document for a fixture by transforming the live one.
 *
 * Deriving beats authoring here. The real nav carries five menus and seventy-five links; a
 * hand-built replacement would differ from production in ways nobody intended, and every one of
 * those differences is a false result waiting to happen. So the fixture keeps the whole live nav
 * and varies only the axis under test.
 *
 * @param {string} navHtml  the live nav document source
 * @param {object} spec     { count, label, links: [{alt, src, caption}], removeLabel }
 */
/**
 * Replace the utility bar's links and language options.
 *
 * The utility bar is the nav's first section: a `<ul>` of author-defined links, followed by a
 * `div.language` block whose first row is the trigger label and whose remaining rows are the
 * language options. Varying those two lists is what the utility-bar tests need — one link to prove
 * there is no dangling separator, one language to check the switcher hides itself, many long links
 * to push the bar toward overflowing.
 *
 * @param {string} navHtml
 * @param {object} spec  { links: ["About Us|/about-us", …], languages: ["English · EN|/", …],
 *                         trigger: ":globe: United States · EN", note, change }
 */
export function transformUtility(navHtml, spec = {}) {
  let out = navHtml;

  if (spec.links) {
    const ulStart = out.indexOf('<ul>');
    const ulEnd = out.indexOf('</ul>', ulStart);
    if (ulStart === -1 || ulEnd === -1) throw new Error('no utility link list found in the source nav');
    const items = spec.links.map((l) => {
      const [label, href] = String(l).split('|');
      return href ? `<li><a href="${esc(href)}">${esc(label)}</a></li>` : `<li>${esc(label)}</li>`;
    }).join('\n');
    out = `${out.slice(0, ulStart)}<ul>\n${items}\n</ul>${out.slice(ulEnd + 5)}`;
  }

  if (spec.languages || spec.trigger) {
    const i = out.indexOf('class="language"');
    if (i === -1) throw new Error('no language block found in the source nav');
    const open = out.lastIndexOf('<div', i);
    let d = 0; let m; let end = open;
    const re = /<div\b[^>]*>|<\/div>/g;
    re.lastIndex = open;
    while ((m = re.exec(out))) {
      if (m[0] !== '</div>') d += 1;
      else { d -= 1; if (d === 0) { end = re.lastIndex; break; } }
    }
    const row = (inner) => `<div><div>${inner}</div></div>`;
    const rows = [row(`<p>${esc(spec.trigger || ':globe: United States · EN')}</p>`)];
    for (const l of spec.languages || []) {
      const [label, href] = String(l).split('|');
      rows.push(row(`<p><a href="${esc(href || '/')}">${esc(label)}</a></p>`));
    }
    if (spec.note) rows.push(row(`<p>${esc(spec.note)}</p>`));
    if (spec.change) {
      const [label, href] = String(spec.change).split('|');
      rows.push(row(`<p><a href="${esc(href || '/')}">${esc(label)}</a></p>`));
    }
    out = `${out.slice(0, open)}<div class="language">\n${rows.join('\n')}\n</div>${out.slice(end)}`;
  }
  return out;
}

export function transformNav(navHtml, spec = {}) {
  // A spec may target more than one region of the same nav. Utility first, so a later brand-strip
  // search runs against the already-edited document rather than a stale copy of it.
  if (spec.utility) {
    const after = transformUtility(navHtml, spec.utility);
    const rest = { ...spec };
    delete rest.utility;
    return Object.keys(rest).length ? transformNav(after, rest) : after;
  }
  const strip = findBrandStrip(navHtml);
  if (!strip) throw new Error('no brand strip found in the source nav — it needs 2+ consecutive image-only links');

  const pool = strip.links;
  const count = spec.count ?? pool.length;
  const built = [];
  for (let i = 0; i < count; i += 1) {
    const base = pool[i % pool.length];
    built.push(editLink(base, (spec.links || [])[i] || {}));
  }

  let out = navHtml.slice(0, strip.start) + built.join('\n') + navHtml.slice(strip.end);

  if (spec.removeLabel) {
    // The label is the paragraph immediately preceding the strip.
    const head = out.slice(0, out.indexOf(built[0] ?? ''));
    const lastP = head.lastIndexOf('<p>');
    if (lastP !== -1) {
      const close = out.indexOf('</p>', lastP);
      if (close !== -1) out = out.slice(0, lastP) + out.slice(close + 4);
    }
  } else if (spec.label) {
    const head = out.slice(0, out.indexOf(built[0] ?? ''));
    const lastP = head.lastIndexOf('<p>');
    if (lastP !== -1) {
      const close = out.indexOf('</p>', lastP);
      if (close !== -1) out = `${out.slice(0, lastP)}<p>${esc(spec.label)}</p>${out.slice(close + 4)}`;
    }
  }
  return out;
}
