/**
 * Rendering DA documents: the shape Document Authoring stores, produced from a fixture spec.
 *
 * The format was read off real documents rather than inferred (see .claude/qa/design-sources.md).
 * Everything in DA is one model:
 *
 *   <body><header></header>
 *     <main>
 *       <div>                          a section
 *         <div class="block variant">  a block; variants are extra class tokens
 *           <div><div>cell</div></div> rows, then cells
 *   <footer></footer></body>
 *
 * There are no tables. Page metadata is `div.metadata` and section metadata
 * `div.section-metadata`, both key/value rows — so metadata needs no special case.
 *
 * No I/O here: everything is a pure string transform, so the awkward part (the nav surgery) is
 * testable against a captured document instead of against a client's live content.
 */

const unesc = (s) => String(s)
  .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#x27;|&apos;/g, "'")
  .replace(/&amp;/g, '&');

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/* --------------------------------------------------------------- primitives */

/** Rows of [key, value] become a metadata-shaped block. */
export function metadataBlock(entries, className = 'metadata') {
  const rows = Object.entries(entries || {})
    .map(([k, v]) => `<div><div><p>${esc(k)}</p></div><div><p>${esc(v)}</p></div></div>`)
    .join('\n');
  return `<div class="${className}">\n${rows}\n</div>`;
}

/** A block: class tokens, then one div per row, one div per cell. */
export function block({ name, variants = [], rows = [] }) {
  const cls = [name, ...variants].filter(Boolean).join(' ');
  const body = rows
    .map((cells) => `<div>${cells.map((c) => `<div>${c}</div>`).join('')}</div>`)
    .join('\n');
  return `<div class="${cls}">\n${body}\n</div>`;
}

/** Wrap sections into the document DA expects. */
export function document_({ sections = [] }) {
  const main = sections.map((s) => `<div>\n${s}\n</div>`).join('\n');
  return `<body>\n<header></header>\n<main>\n${main}\n</main>\n<footer></footer>\n</body>`;
}

/**
 * A fixture page. It carries almost no content of its own — its job is to set metadata (the `nav`
 * override, the `Language` row that drives RTL) and to say what it is, so anyone who stumbles on
 * it in DA knows it is generated and where it came from.
 */
export function fixturePage(fixture, { source } = {}) {
  const heading = [
    `<h2>QA fixture — ${esc(fixture.id)}</h2>`,
    `<p>${esc(fixture.title)}${fixture.purpose ? ` — ${esc(fixture.purpose)}` : ''}</p>`,
    `<p><em>Generated by da-fixture.mjs${source ? ` from ${esc(source)}` : ''}. Do not edit by hand:`
      + ' edit the plan and re-run, or the next run will overwrite you.</em></p>',
  ].join('\n');

  const sections = [heading];
  if (fixture.metadata && Object.keys(fixture.metadata).length) sections.push(metadataBlock(fixture.metadata));
  for (const s of fixture.sections || []) {
    sections.push(block(s));
  }
  return document_({ sections });
}

/* ------------------------------------------------------------- nav surgery */

/**
 * Find the run of image-only links that the implementation classifies as the brand carousel.
 *
 * The strip is not a named block — AC-11 says "a strip of 2+ image-only links renders as the
 * brand carousel", so classification is by content shape at runtime. That means a fixture cannot
 * target it by class; it has to find the same thing the block's own code finds.
 *
 * @returns {{start:number, end:number, links:string[]}|null}
 */
export function findBrandStrip(html) {
  const LINK = /<a\b[^>]*>\s*<picture>[\s\S]*?<\/picture>\s*<\/a>/g;
  const hits = [];
  let m;
  while ((m = LINK.exec(html))) hits.push({ start: m.index, end: LINK.lastIndex, text: m[0] });
  if (hits.length < 2) return null;

  // Consecutive means "separated only by markup, not by other content" — the links sit in
  // sibling paragraphs, so only tags and whitespace may appear between them.
  let run = [hits[0]];
  let best = run;
  for (let i = 1; i < hits.length; i += 1) {
    const between = html.slice(hits[i - 1].end, hits[i].start);
    if (/^[\s]*(<\/?[a-z][^>]*>[\s]*)*$/i.test(between)) run.push(hits[i]);
    else run = [hits[i]];
    if (run.length > best.length) best = run;
  }
  if (best.length < 2) return null;
  return { start: best[0].start, end: best[best.length - 1].end, links: best.map((h) => h.text) };
}

/** Rewrite one link's alt text, and optionally its image source. */
export function editLink(link, { alt, src, caption } = {}) {
  let out = link;
  if (alt !== undefined) out = out.replace(/alt="[^"]*"/g, `alt="${esc(alt)}"`);
  if (src !== undefined) {
    out = out.replace(/src="[^"]*"/g, `src="${esc(src)}"`).replace(/srcset="[^"]*"/g, `srcset="${esc(src)}"`);
  }
  // A caption turns an image-only link into a captioned one, which the implementation must then
  // classify as featured products rather than as a brand carousel.
  if (caption) out = `${out}\n<p>${esc(caption)}</p>`;
  return out;
}

/**
 * Produce a nav document for a fixture by transforming the live one.
 *
 * Deriving beats authoring here. The real nav carries five menus and seventy-five links; a
 * hand-built replacement would differ from production in ways nobody intended, and every one of
 * those differences is a false result waiting to happen. So the fixture keeps the whole live nav
 * and varies only the axis under test.
 *
 * @param {string} navHtml  the live nav document source
 * @param {object} spec     { count, label, links: [{alt, src, caption}], removeLabel }
 */
/**
 * Replace the utility bar's links and language options.
 *
 * The utility bar is the nav's first section: a `<ul>` of author-defined links, followed by a
 * `div.language` block whose first row is the trigger label and whose remaining rows are the
 * language options. Varying those two lists is what the utility-bar tests need — one link to prove
 * there is no dangling separator, one language to check the switcher hides itself, many long links
 * to push the bar toward overflowing.
 *
 * @param {string} navHtml
 * @param {object} spec  { links: ["About Us|/about-us", …], languages: ["English · EN|/", …],
 *                         trigger: ":globe: United States · EN", note, change }
 */
export function transformUtility(navHtml, spec = {}) {
  let out = navHtml;

  if (spec.links) {
    const ulStart = out.indexOf('<ul>');
    const ulEnd = out.indexOf('</ul>', ulStart);
    if (ulStart === -1 || ulEnd === -1) throw new Error('no utility link list found in the source nav');
    const items = spec.links.map((l) => {
      const [label, href] = String(l).split('|');
      return href ? `<li><a href="${esc(href)}">${esc(label)}</a></li>` : `<li>${esc(label)}</li>`;
    }).join('\n');
    out = `${out.slice(0, ulStart)}<ul>\n${items}\n</ul>${out.slice(ulEnd + 5)}`;
  }

  if (spec.languages || spec.trigger) {
    const i = out.indexOf('class="language"');
    if (i === -1) throw new Error('no language block found in the source nav');
    const open = out.lastIndexOf('<div', i);
    let d = 0; let m; let end = open;
    const re = /<div\b[^>]*>|<\/div>/g;
    re.lastIndex = open;
    while ((m = re.exec(out))) {
      if (m[0] !== '</div>') d += 1;
      else { d -= 1; if (d === 0) { end = re.lastIndex; break; } }
    }
    const row = (inner) => `<div><div>${inner}</div></div>`;
    const rows = [row(`<p>${esc(spec.trigger || ':globe: United States · EN')}</p>`)];
    for (const l of spec.languages || []) {
      const [label, href] = String(l).split('|');
      rows.push(row(`<p><a href="${esc(href || '/')}">${esc(label)}</a></p>`));
    }
    if (spec.note) rows.push(row(`<p>${esc(spec.note)}</p>`));
    if (spec.change) {
      const [label, href] = String(spec.change).split('|');
      rows.push(row(`<p><a href="${esc(href || '/')}">${esc(label)}</a></p>`));
    }
    out = `${out.slice(0, open)}<div class="language">\n${rows.join('\n')}\n</div>${out.slice(end)}`;
  }
  return out;
}

/**
 * Replace the nav's tools row — Search, Favorites, Cart, Account.
 *
 * These are author-defined links like any other, but they live in the nav's LAST list rather than
 * its first, which is why `transformUtility` never touched them: it replaces the first `<ul>` and
 * stops. That left an Arabic fixture with an Arabic utility bar, Arabic menus and an English tools
 * row — visible English in a header that was supposed to be entirely translated.
 *
 * Each entry keeps its icon token, so an entry reads ":search: بحث|/search".
 *
 * @param {string} navHtml
 * @param {string[]} tools  ["\:search\: Label|/href", …]
 */
export function transformTools(navHtml, tools) {
  if (!tools) return navHtml;
  const lists = [...navHtml.matchAll(/<ul>[\s\S]*?<\/ul>/g)];
  // "The last list" is not good enough: a megamenu column can be authored as a list too, and on a
  // nav shaped that way the last one is a submenu, not the tools. What actually distinguishes the
  // tools row is that every item is an icon token plus a label — ":search: Search" — so that is what
  // this looks for, taking the last such list.
  const isTools = (u) => /<li>\s*<a\b[^>]*>\s*:[a-z0-9-]+:/i.test(u[0]);
  const target = [...lists].reverse().find(isTools);
  if (!target) {
    throw new Error('no tools list found in the source nav — the tools row is a <ul> whose items are '
      + 'icon tokens like ":search: Search", and no list here looks like that');
  }
  const items = tools.map((t) => {
    const [label, href] = String(t).split('|');
    return href ? `<li><a href="${esc(href)}">${esc(label)}</a></li>` : `<li>${esc(label)}</li>`;
  }).join('\n');
  return `${navHtml.slice(0, target.index)}<ul>\n${items}\n</ul>${navHtml.slice(target.index + target[0].length)}`;
}

/**
 * Match the `</div>` that closes the `<div` starting at `open`, and return the index just past it.
 * Nav regions nest divs several deep, so a non-greedy regex closes on the wrong tag every time.
 */
function closeDiv(html, open) {
  const re = /<div\b[^>]*>|<\/div>/g;
  re.lastIndex = open;
  let depth = 0;
  let m;
  while ((m = re.exec(html))) {
    if (m[0] === '</div>') {
      depth -= 1;
      if (depth === 0) return re.lastIndex;
    } else depth += 1;
  }
  return html.length;
}

/** The direct child `<div>`s of a block — its rows. */
function rowsOf(blockHtml) {
  const inner = blockHtml.slice(blockHtml.indexOf('>') + 1, blockHtml.lastIndexOf('</div>'));
  const rows = [];
  let i = 0;
  while (i < inner.length) {
    const open = inner.indexOf('<div', i);
    if (open === -1) break;
    const end = closeDiv(inner, open);
    rows.push(inner.slice(open, end));
    i = end;
  }
  return rows;
}

/**
 * Replace the nav's logo.
 *
 * The logo is an icon token inside a link — `<a href="/" title="…">:ufs-logo:</a>`. The Content
 * Slots table gives it one fallback ("text brand if no image"), and an author produces that by
 * typing the brand name where the icon token was. So that is exactly what this does: swap the
 * token for text, leaving the link itself alone.
 *
 * @param {string} navHtml
 * @param {object} spec  { text }
 */
export function transformLogo(navHtml, spec = {}) {
  const i = navHtml.indexOf(':ufs-logo:');
  if (i === -1) throw new Error('no logo token found in the source nav');
  if (spec.text === undefined) return navHtml;
  return navHtml.slice(0, i) + esc(spec.text) + navHtml.slice(i + ':ufs-logo:'.length);
}

/**
 * Rebuild the nav's top-level items.
 *
 * Every top-level item is one `div.nav-menu` block: row 1 holds the link that shows on the bar,
 * and rows 2+ are its megamenu columns. A block with only row 1 is a plain link with nothing to
 * open — which is how the content model distinguishes the two, with no flag to set.
 *
 * Items are built by cycling the live blocks, the same way the brand strip cycles logos, so a
 * fixture with six items still carries real megamenu content rather than something invented.
 *
 * @param {string} navHtml
 * @param {object} spec  { items: [{ label, href, plain }] }
 */
/**
 * One labelled column, in the shape the nav actually stores: the heading is a plain `<p>` in the
 * row's first cell and the links are `<p><a>` in its second. No `<strong>` anywhere — that is what
 * separates a column from a tile, so adding one here would silently reclassify the row.
 */
function columnRow(spec = {}) {
  const heading = spec.heading === undefined ? '' : `<p>${esc(spec.heading)}</p>`;
  const links = (spec.links || []).map((l) => {
    const [label, href = '/'] = String(l).split('|');
    return `<p><a href="${esc(href)}">${esc(label)}</a></p>`;
  }).join('');
  return `<div><div>${heading}</div><div>${links}</div></div>`;
}

/**
 * Replace a panel's labelled columns, leaving everything else where it is.
 *
 * A panel is a mix of row kinds — Recipes ships a feature tile, two columns, then a promo tile — and
 * only the columns are being replaced. So they are matched positionally by kind rather than by row
 * number: the first spec entry replaces the first column, and tiles and brand strips are never
 * touched. Extra spec entries are appended just after the last existing column, which keeps them
 * inside the run of columns rather than after a trailing tile.
 *
 * Live columns the spec does not reach are left alone. That is deliberate: a fixture translating the
 * two columns it asserts should not silently blank a third.
 *
 * `exact` is for the other kind of fixture, the one whose whole point is the column count. A panel
 * of one column cannot be authored by replacing the first of three, so `exact` drops the surplus
 * and the list becomes the complete set. It stays opt-in because the lenient behaviour is what a
 * translation fixture wants, and getting that wrong blanks content nobody meant to touch.
 */
function rebuildColumns(panelRows, specs, exact = false) {
  const at = panelRows.map((r, i) => (classifyPanelRow(r) === 'column' ? i : -1)).filter((i) => i >= 0);
  const out = panelRows.slice();
  specs.slice(0, at.length).forEach((spec, n) => { out[at[n]] = columnRow(spec); });
  if (specs.length > at.length) {
    const insertAt = at.length ? at[at.length - 1] + 1 : out.length;
    out.splice(insertAt, 0, ...specs.slice(at.length).map(columnRow));
  } else if (exact) {
    // Drop from the end so the earlier indices stay valid as we go.
    for (const i of at.slice(specs.length).reverse()) out.splice(i, 1);
  }
  return out;
}

export function transformMenus(navHtml, spec = {}) {
  if (!spec.items) return navHtml;
  const MENU = /<div class="nav-menu[^"]*">/g;
  const pool = [];
  let m;
  while ((m = MENU.exec(navHtml))) {
    const end = closeDiv(navHtml, m.index);
    pool.push({ start: m.index, end, text: navHtml.slice(m.index, end) });
    MENU.lastIndex = end;
  }
  if (!pool.length) throw new Error('no nav-menu blocks found in the source nav');

  const built = spec.items.map((item, i) => {
    const base = pool[i % pool.length];
    const rows = rowsOf(base.text);
    const label = item.label === undefined ? null : esc(item.label);
    const href = esc(item.href || '/');
    // Row 1, cell 1 is the bar link. Rewrite it rather than rebuilding the row, so anything else
    // the authors put in that row survives.
    let first = rows[0];
    if (label !== null) {
      // Replace the row's FIRST CELL, not the first `</div>` after the row opens — those are two
      // different tags, and a non-greedy regex takes the wrong one and eats the row itself.
      const cellStart = first.indexOf('<div', first.indexOf('>') + 1);
      const cellEnd = closeDiv(first, cellStart);
      // Keep the <p> wrapper the authors actually use: the stylesheet targets `li > p > a` as well
      // as `li > a`, so dropping it would style the fixture differently from production.
      first = `${first.slice(0, cellStart)}<div><p><a href="${href}">${label}</a></p></div>${first.slice(cellEnd)}`;
    }
    let panel = item.plain ? [] : rows.slice(1);
    // Translating or replacing the panel's columns is what an RTL or expansion fixture needs: the
    // bar label alone leaves every submenu link in the source language.
    if (panel.length && item.columns) panel = rebuildColumns(panel, item.columns, item.columnsExact);
    return `<div class="nav-menu">${[first, ...panel].join('')}</div>`;
  });

  return navHtml.slice(0, pool[0].start) + built.join('') + navHtml.slice(pool[pool.length - 1].end);
}

/* ------------------------------------------------- megamenu promo / feature */

/**
 * Classify one authored panel row the way `normalizeNavMenus` does, so a fixture edits the same
 * thing the implementation will classify. Reading the rule off the code matters here: the row that
 * becomes a promo is defined by what it does NOT have (a list of links in its second cell), so a
 * fixture that guessed "the row with three paragraphs" would drift the moment an author added one.
 *
 * @returns {'brands'|'column'|'tile'}
 */
export function classifyPanelRow(rowHtml) {
  const links = [...rowHtml.matchAll(/<a\b[^>]*>[\s\S]*?<\/a>/g)].map((m) => m[0]);
  const imageLinks = links.filter((a) => /<picture|<img/.test(a));
  if (imageLinks.length >= 2 && imageLinks.length === links.length) return 'brands';
  const cells = rowsOf(rowHtml);
  const second = cells[1] || '';
  // The implementation's own test: a second cell holding links and no <strong> is a labelled
  // column. A <strong> in there means the author wrote a tile's title, not a column of links.
  if (/<a\b/.test(second) && !/<strong>/.test(second)) return 'column';
  return 'tile';
}

/**
 * Author one promo / feature tile as the DA row the nav actually stores.
 *
 * The tile has no block of its own — it is a submenu row whose first cell holds loose paragraphs:
 * eyebrow, **title**, an optional description, and the CTA. `decorateMegamenus` then reads meaning
 * out of that order, so the fixture has to reproduce the order rather than name the parts.
 */
function tileRow(spec = {}) {
  const paras = [];
  if (spec.eyebrow !== undefined) paras.push(`<p>${esc(spec.eyebrow)}</p>`);
  if (spec.title !== undefined) {
    // An author who forgets the bold is a real case: the classifier finds the title by looking for
    // <strong>, and falls back to the second paragraph when there is none.
    paras.push(spec.strongTitle === false ? `<p>${esc(spec.title)}</p>` : `<p><strong>${esc(spec.title)}</strong></p>`);
  }
  if (spec.description !== undefined) paras.push(`<p>${esc(spec.description)}</p>`);

  const ctaP = (value) => {
    const [label, href = '/'] = String(value).split('|');
    // Icons are authored as a literal token; decorateIcons swaps it for the SVG at runtime.
    const icon = spec.ctaIcon ? ' :arrow:' : '';
    return `<p><a href="${esc(href)}">${esc(label)}</a>${icon}</p>`;
  };
  const ctas = [];
  if (spec.cta !== undefined) ctas.push(ctaP(spec.cta));
  // A second CTA is a "forbidden combination" the content model states but nothing enforces.
  if (spec.extraCta !== undefined) ctas.push(ctaP(spec.extraCta));

  // Putting the CTA in the SECOND cell is the mis-authoring that costs the tile its card: a second
  // cell with links and no <strong> is a labelled column, so the whole tile is reclassified.
  if (spec.ctaInSecondCell) return `<div><div>${paras.join('')}</div><div>${ctas.join('')}</div></div>`;
  return `<div><div>${paras.join('')}${ctas.join('')}</div><div></div></div>`;
}

/**
 * Replace, move, insert or remove a megamenu's promo / feature tile.
 *
 * Which of the two a tile becomes is not authored — `decorateMegamenus` calls the panel's FIRST
 * child a light `.nav-feature` and every later one a dark `.nav-promo`. So `position` is the whole
 * variant control: the same authored content is a feature at the top of the panel and a promo
 * anywhere else, which is exactly what AC-13 asks a tester to prove.
 *
 * @param {string} navHtml
 * @param {object|object[]} spec  one edit, or several against different menus:
 *   { menu, target: 'feature'|'promo', position: 'first'|'last', remove, eyebrow, title,
 *     strongTitle, description, cta: 'Label|/href', extraCta, ctaIcon, ctaInSecondCell }
 */
export function transformPromo(navHtml, spec) {
  const edits = Array.isArray(spec) ? spec : [spec];
  let out = navHtml;

  for (const edit of edits) {
    if (!edit) continue;
    const MENU = /<div class="nav-menu[^"]*">/g;
    const blocks = [];
    let m;
    while ((m = MENU.exec(out))) {
      const end = closeDiv(out, m.index);
      blocks.push({ start: m.index, end, text: out.slice(m.index, end) });
      MENU.lastIndex = end;
    }
    if (!blocks.length) throw new Error('no nav-menu blocks found in the source nav');

    // Menus are named by their bar label, which is the trigger row's link text — the only handle a
    // plan author has. Without a name, edit the first menu that already carries a tile.
    const named = edit.menu
      ? blocks.find((b) => {
        const first = rowsOf(b.text)[0] || '';
        const link = first.match(/<a\b[^>]*>([\s\S]*?)<\/a>/);
        // The stored label is escaped — "Training &amp; Inspiration" — but a plan names the menu
        // the way it reads on the bar, so compare decoded rather than making every plan escape.
        return link && unesc(link[1].replace(/<[^>]+>/g, '').trim()) === edit.menu;
      })
      : blocks.find((b) => rowsOf(b.text).slice(1).some((r) => classifyPanelRow(r) === 'tile'));
    if (!named) throw new Error(`no nav-menu found for menu ${JSON.stringify(edit.menu ?? '(any with a tile)')}`);

    const rows = rowsOf(named.text);
    const trigger = rows[0];
    const panel = rows.slice(1);
    const kinds = panel.map(classifyPanelRow);
    // A panel may hold two tiles — Recipes ships a leading feature AND a trailing promo — so an
    // edit says which it means in the reader's own terms rather than by row number.
    const tiles = kinds.map((k, i) => (k === 'tile' ? i : -1)).filter((i) => i >= 0);
    const tileAt = (edit.target === 'promo' ? tiles[tiles.length - 1] : tiles[0]) ?? -1;

    let next = panel.slice();
    if (edit.remove) {
      // A tile that is not there is already removed. This used to throw, which made the fixture's
      // correctness depend on the live nav still having a tile to take away — so when Promotions
      // lost its tile upstream, a fixture asking for "Promotions with no tile" started failing for
      // having got exactly what it asked for, and took the whole plan's generation down with it.
      // What a `remove` states is the shape the fixture wants, not an edit that must land.
      if (tileAt !== -1) next.splice(tileAt, 1);
    } else {
      const row = tileRow(edit);
      if (edit.position === undefined) {
        // Default: edit the tile where it already sits, so a fixture that only changes copy does
        // not silently change the variant as well.
        if (tileAt === -1) next.push(row);
        else next[tileAt] = row;
      } else {
        if (tileAt !== -1) next.splice(tileAt, 1);
        // 'last' must land before the brand strip: the strip spans the panel's full width on its
        // own row, so a tile after it is not "the last column", it is a second full-width row.
        const brandsAt = next.findIndex((r) => classifyPanelRow(r) === 'brands');
        const at = edit.position === 'first' ? 0 : (brandsAt === -1 ? next.length : brandsAt);
        next.splice(at, 0, row);
      }
    }

    const rebuilt = `<div class="nav-menu">${[trigger, ...next].join('')}</div>`;
    out = out.slice(0, named.start) + rebuilt + out.slice(named.end);
  }
  return out;
}

export function transformNav(navHtml, spec = {}) {
  // A spec may target more than one region of the same nav. The other regions run first, so a
  // later brand-strip search reads the already-edited document rather than a stale copy of it.
  let src = navHtml;
  if (spec.utility) src = transformUtility(src, spec.utility);
  // Tools before menus: both are found positionally, and rebuilding the menu blocks first would
  // move the list this one looks for.
  if (spec.tools) src = transformTools(src, spec.tools);
  if (spec.logo) src = transformLogo(src, spec.logo);
  if (spec.menus) src = transformMenus(src, spec.menus);
  if (spec.promo) src = transformPromo(src, spec.promo);

  // The brand strip is only touched when the spec actually asks for it. A fixture that edits the
  // utility bar of a nav whose Products megamenu was left alone must not go rummaging for a strip.
  const wantsStrip = ['count', 'label', 'removeLabel', 'links'].some((k) => spec[k] !== undefined);
  if (!wantsStrip && (spec.utility || spec.tools || spec.logo || spec.menus || spec.promo)) return src;

  const navSrc = src;
  const strip = findBrandStrip(navSrc);
  if (!strip) throw new Error('no brand strip found in the source nav — it needs 2+ consecutive image-only links');

  const pool = strip.links;
  const count = spec.count ?? pool.length;
  const built = [];
  for (let i = 0; i < count; i += 1) {
    const base = pool[i % pool.length];
    built.push(editLink(base, (spec.links || [])[i] || {}));
  }

  let out = navSrc.slice(0, strip.start) + built.join('\n') + navSrc.slice(strip.end);

  if (spec.removeLabel) {
    // The label is the paragraph immediately preceding the strip.
    const head = out.slice(0, out.indexOf(built[0] ?? ''));
    const lastP = head.lastIndexOf('<p>');
    if (lastP !== -1) {
      const close = out.indexOf('</p>', lastP);
      if (close !== -1) out = out.slice(0, lastP) + out.slice(close + 4);
    }
  } else if (spec.label) {
    const head = out.slice(0, out.indexOf(built[0] ?? ''));
    const lastP = head.lastIndexOf('<p>');
    if (lastP !== -1) {
      const close = out.indexOf('</p>', lastP);
      if (close !== -1) out = `${out.slice(0, lastP)}<p>${esc(spec.label)}</p>${out.slice(close + 4)}`;
    }
  }
  return out;
}

/* ---------------------------------------------------------- footer surgery */

/**
 * The footer is derived from the live `/footer` document for the same reason the nav is: it
 * carries three link columns, fourteen links and five social accounts, and a hand-built
 * replacement would differ from production in ways nobody chose. The fixture keeps the whole
 * document and varies only the axis under test.
 *
 * The footer is reached differently from the nav, though. `footer.js` reads `getMetadata('footer')`
 * and falls back to `/footer`, so a fixture page points at its own footer document with a `footer`
 * metadata row — the same mechanism as `nav`, a different key.
 *
 * `decorate()` is positional: it destructures the document's sections as
 * `[newsletter, columns, bottom]`. So this transform is positional too. Matching the
 * implementation's own rule is the point — a transform that searched for the bottom bar by
 * content would edit a section the block never treats as one.
 */

/** The direct child `<div>`s of `<main>` — a DA document's sections. */
function mainSections(html) {
  const open = html.indexOf('<main>');
  const close = html.lastIndexOf('</main>');
  if (open === -1 || close === -1) throw new Error('no <main> element in the source document');
  const sections = [];
  let i = open + '<main>'.length;
  while (i < close) {
    const start = html.indexOf('<div', i);
    if (start === -1 || start >= close) break;
    const end = closeDiv(html, start);
    sections.push({ start, end, text: html.slice(start, end) });
    i = end;
  }
  return sections;
}

/** Paragraphs, in document order. They do not nest, so a flat scan is exact rather than a guess. */
function paras(html) {
  return [...html.matchAll(/<p\b[^>]*>[\s\S]*?<\/p>/g)]
    .map((m) => ({ start: m.index, end: m.index + m[0].length, text: m[0] }));
}

const splice = (html, at, text = '') => html.slice(0, at.start) + text + html.slice(at.end);

const LOGO_TOKEN = ':ufs-logo:';

/**
 * The newsletter band — section one, the standalone `newsletter` block.
 *
 * Its cell holds a heading, a paragraph of body copy, and a link that `newsletter.js` turns into
 * the Subscribe form. Which paragraph is which is decided by whether it holds a link, exactly as
 * the block's own decorator decides it.
 *
 * @param {string} html
 * @param {object} spec  { remove, heading, headingLevel, removeHeading, subtext, removeSubtext,
 *                         cta: 'Label|/href', removeCta }
 */
function editBand(html, spec = {}) {
  if (spec.remove) return null;
  let out = html;

  const hm = /<h[1-6]\b[^>]*>[\s\S]*?<\/h[1-6]>/.exec(out);
  if (spec.removeHeading) {
    if (!hm) throw new Error('no heading found in the newsletter band');
    out = splice(out, { start: hm.index, end: hm.index + hm[0].length });
  } else if (spec.heading !== undefined || spec.headingLevel !== undefined) {
    if (!hm) throw new Error('no heading found in the newsletter band');
    // The authored level is worth varying rather than fixing: footer.js promotes whatever it finds
    // to an h2 so the footer does not skip a level after the page's h1, and a fixture that authors
    // an h2 directly proves the already-correct path as well as the promotion.
    const level = spec.headingLevel ?? /<h([1-6])/.exec(hm[0])[1];
    const text = spec.heading ?? hm[0].replace(/<[^>]+>/g, '');
    // The authored id is dropped rather than carried over: the pipeline derives one from the text,
    // and keeping a stale slug on retitled copy is a difference no test asked for.
    out = splice(out, { start: hm.index, end: hm.index + hm[0].length }, `<h${level}>${esc(text)}</h${level}>`);
  }

  // Body copy is a paragraph with no link in it; the CTA is the one that has a link.
  const sub = () => paras(out).find((p) => !/<a\b/.test(p.text));
  if (spec.removeSubtext) {
    const p = sub();
    if (p) out = splice(out, p);
  } else if (spec.subtext !== undefined) {
    const p = sub();
    if (p) out = splice(out, p, `<p>${esc(spec.subtext)}</p>`);
  }

  const ctaP = paras(out).find((p) => /<a\b/.test(p.text));
  if (spec.removeCta) {
    // No link means no form at all — the band keeps its heading and copy and renders nothing else,
    // which is the "required slot absent" case the Content Slots table calls for.
    if (ctaP) out = splice(out, ctaP);
  } else if (spec.cta !== undefined) {
    const [label, href = '/subscribe'] = String(spec.cta).split('|');
    const rebuilt = `<p><a href="${esc(href)}">${esc(label)}</a></p>`;
    out = ctaP ? splice(out, ctaP, rebuilt) : out.replace(/<\/div>\s*$/, `${rebuilt}</div>`);
  }
  return out;
}

/**
 * The link columns — section two: the brand column, then a heading paragraph and a list per column.
 *
 * There are no column `<div>`s in the document. DA flattens them, and `decorate()` rebuilds them by
 * starting a new column at every `<p>` that holds a `<strong>` and no image. So `strongHeading:
 * false` is not a cosmetic option — it is the authoring mistake that silently merges two columns,
 * and the only way to author it is to leave the bold off.
 *
 * @param {string} html
 * @param {object} spec  { brand: { logoText, removeLogo, tagline: 'lead|accent', removeTagline },
 *                         columns: [{ heading, strongHeading, links: ['Label|/href'] }] }
 */
function editColumns(html, spec = {}) {
  const brand = spec.brand || {};
  let out = html;

  if (brand.removeLogo || brand.logoText !== undefined) {
    const i = out.indexOf(LOGO_TOKEN);
    if (i === -1) throw new Error(`no ${LOGO_TOKEN} token found in the source footer`);
    if (brand.logoText !== undefined) {
      // The Content Slots table gives the logo one fallback — a text brand — and an author
      // produces it by typing the name where the icon token was. So that is what this does.
      out = out.slice(0, i) + esc(brand.logoText) + out.slice(i + LOGO_TOKEN.length);
    } else {
      const p = paras(out).find((q) => q.start <= i && q.end >= i);
      if (p) out = splice(out, p);
    }
  }

  const taglineOf = () => paras(out).find((p) => /<br\s*\/?>/.test(p.text));
  if (brand.removeTagline) {
    const t = taglineOf();
    if (t) out = splice(out, t);
  } else if (brand.tagline !== undefined) {
    const [lead, accent] = String(brand.tagline).split('|');
    const t = taglineOf();
    // No `|` means no <br>, and no <br> means decorate() finds nothing to wrap in the script
    // accent. That is a degraded case worth being able to author, not an accident.
    const rebuilt = accent === undefined ? `<p>${esc(lead)}</p>` : `<p>${esc(lead)}<br>${esc(accent)}</p>`;
    if (t) out = splice(out, t, rebuilt);
  }

  if (spec.columns) {
    const first = out.search(/<p><strong>/);
    const lastUl = out.lastIndexOf('</ul>');
    if (first === -1 || lastUl === -1) throw new Error('no link columns found in the source footer');
    const built = spec.columns.map((c) => {
      const items = (c.links || []).map((l) => {
        const [label, href] = String(l).split('|');
        return href ? `<li><a href="${esc(href)}">${esc(label)}</a></li>` : `<li>${esc(label)}</li>`;
      }).join('\n');
      const head = c.heading === undefined ? ''
        : `${c.strongHeading === false ? `<p>${esc(c.heading)}</p>` : `<p><strong>${esc(c.heading)}</strong></p>`}\n`;
      return `${head}<ul>\n${items}\n</ul>`;
    }).join('\n');
    // An empty array is meaningful: every link column gone, brand column alone.
    out = out.slice(0, first) + built + out.slice(lastUl + '</ul>'.length);
  }
  return out;
}

/**
 * The bottom bar — section three: a copyright paragraph and a paragraph of social icon links.
 *
 * `decorate()` finds the social row as "the child holding an `.icon`" and gives each icon-only link
 * an `aria-label` derived from its hostname. A social entry therefore carries both a label and a
 * URL, and the icon token is derived from the label unless one is given.
 *
 * @param {string} html
 * @param {object} spec  { remove, copyright, removeCopyright,
 *                         socials: ['Instagram|https://…|instagram'], removeSocials }
 */
function editBottom(html, spec = {}) {
  if (spec.remove) return null;
  let out = html;

  const copyOf = () => paras(out).find((p) => !/<a\b/.test(p.text));
  if (spec.removeCopyright) {
    const p = copyOf();
    if (p) out = splice(out, p);
  } else if (spec.copyright !== undefined) {
    const p = copyOf();
    if (p) out = splice(out, p, `<p>${esc(spec.copyright)}</p>`);
  }

  const socialP = paras(out).find((p) => /<a\b/.test(p.text));
  if (spec.removeSocials) {
    if (socialP) out = splice(out, socialP);
  } else if (spec.socials) {
    const links = spec.socials.map((s) => {
      const [label, href = '#', token] = String(s).split('|');
      // "TikTok" authors as :tiktok:, which is also what the hostname-derived accessible name
      // will be compared against.
      const icon = token || label.toLowerCase().replace(/[^a-z0-9]+/g, '');
      return `<a href="${esc(href)}" title="${esc(label)}">:${esc(icon)}:</a>`;
    }).join('');
    const rebuilt = `<p>${links}</p>`;
    out = socialP ? splice(out, socialP, rebuilt) : out.replace(/<\/div>\s*$/, `${rebuilt}</div>`);
  }
  return out;
}

/**
 * Produce a footer document for a fixture by transforming the live one.
 *
 * @param {string} footerHtml  the live footer document source
 * @param {object} spec        { newsletter, brand, columns, bottom } — see the editors above
 */
export function transformFooter(footerHtml, spec = {}) {
  const secs = mainSections(footerHtml);
  if (secs.length < 3) {
    throw new Error(`the source footer has ${secs.length} section(s); decorate() destructures three `
      + '— newsletter band, link columns, bottom bar');
  }
  const parts = [
    editBand(secs[0].text, spec.newsletter),
    editColumns(secs[1].text, spec),
    editBottom(secs[2].text, spec.bottom),
    // Anything an author added beyond the three the block reads is carried through untouched:
    // dropping it would make the fixture differ from production on an axis nobody chose.
    ...secs.slice(3).map((s) => s.text),
  ].filter((p) => p != null);

  return footerHtml.slice(0, secs[0].start) + parts.join('\n') + footerHtml.slice(secs[secs.length - 1].end);
}
