/**
 * The renderer, and in particular the nav surgery.
 *
 * The surgery is the risky part: it locates the brand strip the same way the implementation does
 * — by content shape, not by class, because AC-11 defines the carousel as "a strip of 2+ image-only
 * links" and nothing in the markup names it. Getting that wrong silently produces a fixture that
 * tests something other than what it claims, so it is pinned against a captured nav sample rather
 * than exercised against the client's live content.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  metadataBlock, block, document_, fixturePage, findBrandStrip, editLink, transformNav, transformUtility,
  transformMenus, transformLogo, transformPromo, classifyPanelRow,
} from '../lib/da-render.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const NAV = readFileSync(join(HERE, 'fixtures', 'nav-sample.html'), 'utf8');
// A second sample, trimmed from the real /nav, because the top-level items have a shape the older
// sample does not: one div.nav-menu per item, row 1 the bar link, rows 2+ the megamenu columns.
const MENUS = readFileSync(join(HERE, 'fixtures', 'nav-menus-sample.html'), 'utf8');
const countLinks = (s) => (s.match(/<a\b[^>]*>\s*<picture>/g) || []).length;

/* -------------------------------------------------------------- primitives */

test('metadataBlock: key/value rows in DA shape', () => {
  const out = metadataBlock({ nav: '/drafts/qa/brands/nav-happy', Language: 'ar-MA' });
  assert.match(out, /<div class="metadata">/);
  assert.match(out, /<div><div><p>nav<\/p><\/div><div><p>\/drafts\/qa\/brands\/nav-happy<\/p><\/div><\/div>/);
  assert.match(out, /<p>Language<\/p><\/div><div><p>ar-MA<\/p>/);
});

test('metadataBlock: escapes values rather than emitting raw markup', () => {
  assert.match(metadataBlock({ Title: 'Sauces & <b>Condiments</b>' }), /Sauces &amp; &lt;b&gt;Condiments/);
});

test('block: variants are extra class tokens, rows and cells nest', () => {
  const out = block({ name: 'feature-grid', variants: ['columns-4', 'plain'], rows: [['<p>a</p>', '<p>b</p>']] });
  assert.match(out, /<div class="feature-grid columns-4 plain">/);
  assert.match(out, /<div><div><p>a<\/p><\/div><div><p>b<\/p><\/div><\/div>/);
});

test('document_: header, main with a div per section, footer', () => {
  const out = document_({ sections: ['<h2>One</h2>', '<h2>Two</h2>'] });
  assert.match(out, /^<body>\n<header><\/header>\n<main>/);
  assert.match(out, /<\/main>\n<footer><\/footer>\n<\/body>$/);
  assert.equal((out.match(/<div>\n<h2>/g) || []).length, 2);
});

test('fixturePage: identifies itself and carries its metadata', () => {
  const out = fixturePage({
    id: 'BRANDS-FX-01',
    title: 'Happy path',
    purpose: '8 logos',
    metadata: { nav: '/drafts/qa/brands/nav-happy' },
  }, { source: '/nav' });
  assert.match(out, /QA fixture — BRANDS-FX-01/);
  assert.match(out, /Generated by da-fixture\.mjs from \/nav/);
  assert.match(out, /Do not edit by hand/);
  assert.match(out, /<div class="metadata">/);
});

/* ------------------------------------------------------------ finding it */

test('findBrandStrip: finds the run of consecutive image-only links', () => {
  const strip = findBrandStrip(NAV);
  assert.ok(strip, 'a strip should be found');
  assert.equal(strip.links.length, 4);
  assert.match(strip.links[0], /alt="Alpha"/);
});

test('findBrandStrip: a single image link is not a strip', () => {
  const one = '<div><a href="/x"><picture><img src="a.png" alt="A"></picture></a></div>';
  assert.equal(findBrandStrip(one), null);
});

// A captioned link is still an <a><picture>, so the run is found — but the block classifies it as
// featured products. The fixture's job is to produce that input, not to judge it.
test('findBrandStrip: text between links breaks the run', () => {
  const split = NAV.replace('alt="Beta">\n</picture>\n</a>', 'alt="Beta">\n</picture>\n</a>\n<p>interrupting copy</p>');
  const strip = findBrandStrip(split);
  assert.ok(strip.links.length < 4, 'the run should be broken by intervening content');
});

/* ---------------------------------------------------------- editing links */

test('editLink: replaces alt and image source, and can add a caption', () => {
  const [first] = findBrandStrip(NAV).links;
  const edited = editLink(first, { alt: 'Renamed', src: 'https://example.test/broken.png', caption: 'A caption' });
  assert.match(edited, /alt="Renamed"/);
  assert.match(edited, /src="https:\/\/example\.test\/broken\.png"/);
  assert.match(edited, /srcset="https:\/\/example\.test\/broken\.png"/);
  assert.match(edited, /<p>A caption<\/p>/);
});

/* ------------------------------------------------------------- transform */

test('transformNav: grows the strip by cycling the available logos', () => {
  const out = transformNav(NAV, { count: 8 });
  assert.equal(countLinks(out), 8 + 0, 'eight brand links');
  assert.match(out, /Recipes/, 'the rest of the nav is untouched');
  assert.match(out, /Our brands:/, 'the label survives');
});

test('transformNav: shrinks the strip', () => {
  assert.equal(countLinks(transformNav(NAV, { count: 2 })), 2);
  assert.equal(countLinks(transformNav(NAV, { count: 1 })), 1);
});

test('transformNav: per-link overrides land on the right links', () => {
  const out = transformNav(NAV, {
    count: 3,
    links: [{}, { alt: 'Broken brand', src: 'https://example.test/missing.png' }, {}],
  });
  assert.match(out, /alt="Broken brand"/);
  assert.match(out, /example\.test\/missing\.png/);
  assert.equal(countLinks(out), 3);
});

test('transformNav: captions turn the strip into the featured-products case', () => {
  const out = transformNav(NAV, { count: 2, links: [{ caption: 'Knorr range' }, { caption: 'Hellmann\'s range' }] });
  assert.match(out, /<p>Knorr range<\/p>/);
  assert.match(out, /Hellmann&#x27;s range|Hellmann's range/);
});

test('transformNav: replaces or removes the label', () => {
  assert.match(transformNav(NAV, { count: 2, label: 'Unsere Marken:' }), /Unsere Marken:/);
  const bare = transformNav(NAV, { count: 2, removeLabel: true });
  assert.doesNotMatch(bare, /Our brands:/);
  assert.equal(countLinks(bare), 2, 'removing the label does not disturb the links');
});

test('transformNav: refuses a source with no strip rather than producing a silent dud', () => {
  assert.throws(() => transformNav('<body><main><div><p>nothing here</p></div></main></body>'),
    /no brand strip found/);
});

/* ------------------------------------------------------- utility bar */

// Scope both helpers to the utility bar. The nav menus have their own <li> and <a>, so counting
// across the whole document measures the wrong thing — which is exactly what it did first time.
const utilitySection = (s) => s.slice(s.indexOf('<main>'), s.indexOf('class="nav-menu"'));
const countLi = (s) => (utilitySection(s).match(/<li>/g) || []).length;
const langRows = (s) => {
  const u = utilitySection(s);
  return (u.slice(u.indexOf('class="language"')).match(/<a /g) || []).length;
};

test('transformUtility: replaces the utility links', () => {
  const out = transformUtility(NAV, { links: ['Only Link|/only'] });
  assert.equal(countLi(out), 1, 'one utility link');
  assert.match(out, /<a href="\/only">Only Link<\/a>/);
  assert.doesNotMatch(out, /About Us/);
  assert.match(out, /Recipes/, 'the rest of the nav is untouched');
});

test('transformUtility: replaces the language options and the trigger', () => {
  const out = transformUtility(NAV, {
    trigger: ':globe: Morocco · AR',
    languages: ['العربية · AR|/ar', 'Français · FR|/fr'],
  });
  assert.match(out, /Morocco · AR/);
  assert.match(out, /href="\/ar"/);
  assert.match(out, /href="\/fr"/);
  assert.doesNotMatch(out, /Deutsch/);
});

// AC-6's case: a market with one language should not get a switcher at all.
test('transformUtility: can produce a single-language block', () => {
  const out = transformUtility(NAV, { languages: ['English · EN|/'] });
  assert.equal(langRows(out), 1, 'exactly one language option');
});

test('transformUtility: refuses a nav with no utility bar rather than silently doing nothing', () => {
  assert.throws(() => transformUtility('<body><main><div><p>nothing</p></div></main></body>', { links: ['A|/a'] }),
    /no utility link list/);
});

test('transformNav: a spec can target the utility bar and the brand strip together', () => {
  const out = transformNav(NAV, { utility: { links: ['Solo|/solo'] }, count: 3 });
  assert.equal(countLi(out), 1, 'utility bar edited');
  assert.equal((out.match(/<a\b[^>]*>\s*<picture>/g) || []).length, 3, 'brand strip edited too');
});

/* ------------------------------------------------------ top-level nav items */

const menuBlocks = (s) => (s.match(/<div class="nav-menu">/g) || []).length;
const barLabels = (s) => [...s.matchAll(/<div class="nav-menu"><div><div><p><a href="[^"]*">([^<]*)</g)].map((m) => m[1]);

test('transformMenus: rebuilds the bar links, keeping the megamenu columns', () => {
  const out = transformMenus(MENUS, { items: [{ label: 'Products', href: '/products' }] });
  assert.equal(menuBlocks(out), 1);
  assert.deepEqual(barLabels(out), ['Products']);
  assert.match(out, /Chef&#x27;s Pick|Chef's Pick/, 'the columns came along');
});

// The content model has no flag for "plain link" — an item is plain when it has nothing but row 1.
test('transformMenus: a plain item is one with no megamenu rows', () => {
  const out = transformMenus(MENUS, { items: [{ label: 'Loyalty Program', href: '/loyalty', plain: true }] });
  assert.doesNotMatch(out.slice(out.indexOf('nav-menu')), /Chef/, 'no columns survive');
  assert.match(out, /<a href="\/loyalty">Loyalty Program<\/a>/);
});

test('transformMenus: keeps the <p> wrapper production authoring uses', () => {
  const out = transformMenus(MENUS, { items: [{ label: 'Recipes', href: '/recipes' }] });
  assert.match(out, /<div><p><a href="\/recipes">Recipes<\/a><\/p><\/div>/);
});

test('transformMenus: cycles the live blocks when more items are wanted than exist', () => {
  const items = ['One', 'Two', 'Three', 'Four', 'Five'].map((label, i) => ({ label, href: `/x${i}` }));
  const out = transformMenus(MENUS, { items });
  assert.equal(menuBlocks(out), 5);
  assert.deepEqual(barLabels(out), ['One', 'Two', 'Three', 'Four', 'Five']);
});

test('transformMenus: leaves the rest of the nav alone', () => {
  const out = transformMenus(MENUS, { items: [{ label: 'Solo', href: '/solo' }] });
  assert.match(out, /About Us/, 'utility bar untouched');
  assert.match(out, /:ufs-logo:/, 'logo untouched');
  assert.match(out, /:cart:/, 'tools untouched');
});

test('transformMenus: refuses a nav with no top-level items', () => {
  assert.throws(() => transformMenus('<body><main><div><p>nothing</p></div></main></body>', { items: [{ label: 'A' }] }),
    /no nav-menu blocks/);
});

/* ------------------------------------------------------------------- logo */

test('transformLogo: swaps the icon token for the text fallback, keeping the link', () => {
  const out = transformLogo(MENUS, { text: 'Unilever Food Solutions' });
  assert.match(out, /<a href="\/" title="Unilever Home">Unilever Food Solutions<\/a>/);
  assert.doesNotMatch(out, /:ufs-logo:/);
});

test('transformLogo: refuses a nav with no logo rather than silently doing nothing', () => {
  assert.throws(() => transformLogo('<body><main><div><p>nothing</p></div></main></body>', { text: 'X' }),
    /no logo token/);
});

/* ----------------------------------------------------------- region routing */

// The brand strip lives inside the Products megamenu. A fixture that only edits the bar must not
// go looking for it — this sample has no strip at all, so a stray search would throw.
test('transformNav: leaves the brand strip alone unless the spec asks for it', () => {
  const out = transformNav(MENUS, { menus: { items: [{ label: 'Solo', href: '/solo' }] } });
  assert.equal(menuBlocks(out), 1);
});

test('transformNav: applies logo, menus and utility to the same document', () => {
  const out = transformNav(MENUS, {
    logo: { text: 'UFS' },
    menus: { items: [{ label: 'Solo', href: '/solo', plain: true }] },
    utility: { links: ['Only|/only'] },
  });
  assert.match(out, /">UFS</);
  assert.match(out, /<a href="\/solo">Solo<\/a>/);
  assert.match(out, /<a href="\/only">Only<\/a>/);
});


/* ------------------------------------------------- megamenu promo / feature */

// The tile has no class and no block of its own — which of the two variants it becomes is decided
// by where it sits in the panel. So these pin the classification rule, not just the copy: a fixture
// that put the tile in the wrong place would test the other variant without ever saying so.

test('classifyPanelRow: a second cell of links is a column, one with a title is a tile', () => {
  const column = '<div><div><p>By Cuisine</p></div><div><p><a href="/a">Asian</a></p></div></div>';
  const tile = '<div><div><p>New Arrival</p><p><strong>T</strong></p><p><a href="/x">Go</a></p></div><div></div></div>';
  const brands = '<div><div><p><a href="/a"><picture></picture></a></p><p><a href="/b"><picture></picture></a></p></div><div></div></div>';
  assert.equal(classifyPanelRow(column), 'column');
  assert.equal(classifyPanelRow(tile), 'tile');
  assert.equal(classifyPanelRow(brands), 'brands');
});

test('classifyPanelRow: a lone image link is a tile CTA, not a two-logo strip', () => {
  const one = '<div><div><p>Eyebrow</p></div><div><p><a href="/a"><picture></picture></a></p></div></div>';
  assert.notEqual(classifyPanelRow(one), 'brands');
});

test('transformPromo: rewrites the tile in place, leaving the columns alone', () => {
  const out = transformPromo(MENUS, {
    menu: 'Recipes', eyebrow: 'Chef’s Pick', title: 'Two-Minute Meals', cta: 'Browse|/recipes/all',
  });
  assert.match(out, /<p>Chef’s Pick<\/p><p><strong>Two-Minute Meals<\/strong><\/p>/);
  assert.match(out, /<a href="\/recipes\/all">Browse<\/a>/);
  assert.ok(out.includes('By Cuisine'), 'the link columns survive');
  assert.ok(!out.includes('20-Minute Weeknight Recipes'), 'the old copy is gone');
});

test('transformPromo: position is the variant control — first is a feature, later a promo', () => {
  const first = transformPromo(MENUS, { menu: 'Recipes', position: 'first', title: 'T', cta: 'C|/c' });
  const last = transformPromo(MENUS, { menu: 'Recipes', position: 'last', title: 'T', cta: 'C|/c' });
  assert.ok(first.indexOf('<strong>T</strong>') < first.indexOf('By Cuisine'), 'leads the panel');
  assert.ok(last.indexOf('<strong>T</strong>') > last.indexOf('By Cuisine'), 'follows the columns');
});

test('transformPromo: a panel with two tiles edits the one the spec names', () => {
  const promo = transformPromo(MENUS, { menu: 'Recipes', target: 'promo', title: 'Only The Promo', cta: 'C|/c' });
  assert.ok(promo.includes('20-Minute Weeknight Recipes'), 'the leading feature is untouched');
  assert.ok(!promo.includes('Mastering Umami'), 'the trailing promo is the one replaced');
});

test('transformPromo: optional slots are omitted rather than emitted empty', () => {
  const out = transformPromo(MENUS, { menu: 'Recipes', eyebrow: 'E', title: 'T' });
  const start = out.lastIndexOf('<div>', out.indexOf('<div><p>E</p>'));
  const row = out.slice(start, start + closeOf(out.slice(start)));
  assert.ok(!/<p><\/p>/.test(row), 'no empty paragraph stands in for the missing CTA');
  assert.ok(!/<a\b/.test(row), 'and no empty anchor either');
});

test('transformPromo: strongTitle:false is the author who forgot the bold', () => {
  const out = transformPromo(MENUS, { menu: 'Recipes', eyebrow: 'E', title: 'T', strongTitle: false, cta: 'C|/c' });
  assert.ok(!out.includes('<strong>T</strong>'));
  assert.match(out, /<p>E<\/p><p>T<\/p>/);
});

test('transformPromo: a CTA in the second cell is the mis-authoring that costs the card', () => {
  const out = transformPromo(MENUS, {
    menu: 'Recipes', eyebrow: 'E', title: 'T', strongTitle: false, cta: 'C|/c', ctaInSecondCell: true,
  });
  // Same rule the implementation applies: links in the second cell and no <strong> means column.
  const row = out.slice(out.indexOf('<div><div><p>E</p>'));
  assert.equal(classifyPanelRow(row.slice(0, closeOf(row))), 'column');
});

// The row ends where its opening <div> is closed; the test needs that to hand one row to the
// classifier rather than the rest of the document.
function closeOf(html) {
  const re = /<div\b[^>]*>|<\/div>/g;
  let depth = 0;
  let m;
  while ((m = re.exec(html))) {
    if (m[0] === '</div>') { depth -= 1; if (depth === 0) return re.lastIndex; } else depth += 1;
  }
  return html.length;
}

test('transformPromo: extraCta authors the second CTA the content model forbids', () => {
  const out = transformPromo(MENUS, { menu: 'Recipes', title: 'T', cta: 'One|/1', extraCta: 'Two|/2' });
  assert.match(out, /<a href="\/1">One<\/a>/);
  assert.match(out, /<a href="\/2">Two<\/a>/);
});

test('transformPromo: ctaIcon authors the arrow token the CSS sizes', () => {
  const out = transformPromo(MENUS, { menu: 'Recipes', title: 'T', cta: 'Go|/g', ctaIcon: true });
  assert.match(out, /<a href="\/g">Go<\/a> :arrow:/);
});

test('transformPromo: remove drops the tile and nothing else', () => {
  const out = transformPromo(MENUS, { menu: 'Recipes', remove: true });
  assert.ok(!out.includes('20-Minute Weeknight Recipes'));
  assert.ok(out.includes('By Cuisine') && out.includes('All Recipes'), 'the columns survive');
});

test('transformPromo: escapes authored text rather than emitting markup', () => {
  const out = transformPromo(MENUS, { menu: 'Recipes', title: 'Sauces & <b>Ketchup</b>', cta: 'C|/c' });
  assert.match(out, /Sauces &amp; &lt;b&gt;Ketchup/);
});

test('transformPromo: several edits apply in one pass, each to its own tile', () => {
  const out = transformPromo(MENUS, [
    { menu: 'Recipes', target: 'feature', eyebrow: 'Chef’s Pick', title: 'The Feature', cta: 'A|/a' },
    { menu: 'Recipes', target: 'promo', eyebrow: 'Trending Now', title: 'The Promo', cta: 'B|/b' },
  ]);
  assert.ok(out.includes('The Feature') && out.includes('The Promo'));
  assert.ok(out.indexOf('The Feature') < out.indexOf('By Cuisine'), 'the feature still leads');
  assert.ok(out.indexOf('The Promo') > out.indexOf('By Cuisine'), 'the promo still follows');
});

test('transformPromo: a menu is named as it reads on the bar, entities and all', () => {
  const amp = MENUS.replace('>Recipes<', '>Training &amp; Inspiration<');
  const out = transformPromo(amp, { menu: 'Training & Inspiration', title: 'T', cta: 'C|/c' });
  assert.match(out, /<strong>T<\/strong>/);
});

test('transformPromo: refuses a menu it cannot find rather than editing the wrong one', () => {
  assert.throws(() => transformPromo(MENUS, { menu: 'Nope', title: 'T' }), /no nav-menu found for menu/);
});

test('transformNav: the promo region composes with the others', () => {
  const out = transformNav(MENUS, {
    logo: { text: 'UFS' },
    promo: { menu: 'Recipes', eyebrow: 'E', title: 'T', cta: 'C|/c' },
  });
  assert.ok(out.includes('UFS') && !out.includes(':ufs-logo:'));
  assert.match(out, /<p>E<\/p><p><strong>T<\/strong><\/p>/);
});
